language: node_js
node_js: stable

before_script:
  - npm install -g yarn
  - npm install -g wepback
  - npm install -g mocha
  - npm install
  - yarn example_server &
  - sleep 10s
  - curl http://127.0.0.1:8080/example/base_func/index.html

after_script:
    - npm run coveralls
